#!/bin/sh

PKG=tanarky
VENV=/usr/share/pyenv/tanarky
USER=`whoami`:staff

sudo mkdir -p $VENV /etc/$PKG
sudo chown -R $USER $VENV
sudo port selfupdate
sudo port install python27 python26 py27-virtualenv
/opt/local/bin/virtualenv-2.7 $VENV --distribute --python=/opt/local/bin/python2.7
ln -s $VENV/bin/activate bin/activate


