.PHONY: small-white small-black medium-white medium-black server

small-white:
	rst2s5.py --theme=$@ presentation.rst index.html

small-black:
	rst2s5.py --theme=$@ presentation.rst index.html

medium-white:
	rst2s5.py --theme=$@ presentation.rst index.html

medium-black:
	rst2s5.py --theme=$@ presentation.rst index.html